services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-compute_node_db}
      POSTGRES_USER: ${POSTGRES_USER:-compute_node_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-compute_node_password}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-compute_node_user} -d ${POSTGRES_DB:-compute_node_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=postgres://compute_node_user:compute_node_password@postgres:5432/compute_node_db
    env_file:
      - .env
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data:
