services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-compute_node_db}
      POSTGRES_USER: ${POSTGRES_USER:-compute_node_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-compute_node_password}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-compute_node_user} -d ${POSTGRES_DB:-compute_node_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
