{{- if .Values.server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "compute-node.serverServiceName" . }}
  labels:
    {{- include "compute-node.nodeLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.server.ports.main }}
    targetPort: http
    protocol: TCP
  - name: admin
    port: {{ .Values.server.ports.admin }}
    targetPort: admin
    protocol: TCP
  selector:
    {{- include "compute-node.nodeSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}

{{- if .Values.worker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "compute-node.workerServiceName" . }}
  labels:
    {{- include "compute-node.nodeLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "compute-node.nodeSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}

{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "compute-node.uiServiceName" . }}
  labels:
    {{- include "compute-node.nodeLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.ui.port | default 3000 }}
    targetPort: {{ .Values.ui.port | default 3000 }}
    protocol: TCP
  selector:
    {{- include "compute-node.nodeSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
