{{- if .Values.security.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlm-node.secretName" . }}
  labels:
    {{- include "vlm-node.nodeLabels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.security.appKey | b64enc | quote }}
  APP_SECRET: {{ .Values.security.appSecret | b64enc | quote }}
  
  # Database URL - this should be base64 encoded
  {{- if .Values.postgresql.url }}
  POSTGRES_URL: {{ .Values.postgresql.url | b64enc | quote }}
  {{- else }}
  POSTGRES_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" 
    (.Values.postgresql.auth.username | default "compute_node_user")
    (.Values.postgresql.auth.password | default "changeme")
    (.Values.postgresql.fullnameOverride | default (printf "%s-postgresql" (include "vlm-node.fullname" .)))
    (.Values.postgresql.primary.service.port | default "5432")
    (.Values.postgresql.auth.database | default "compute_node_db") | b64enc | quote }}
  {{- end }}
{{- end }}
