name: Build UI

on:
  push:
    branches: [ main, 'feature/*', 'fix/*', 'chore/*' ]
    paths:
      - 'ui/**'
      - '.github/workflows/build-ui.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/vlm-ui
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=raw,enable=${{ inputs.extra_tag != '' }},value=${{ inputs.extra_tag }}
            type=match,pattern=(\w+-)?(v\d+\.\d+\.\d+),group=2
            type=match,pattern=(\w+-)?(v\d+\.\d+),group=2
            type=match,pattern=(\w+-)?(v\d+),group=2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ui
        push: true
        tags: ${{ steps.docker-metadata.outputs.tags }}
